{
  "name": "cosmos",
  "version": "0.0.1",
  "author": "acheede@processmap.com, kuppula@processmap.com, ssbehera@processmap.com",
  "description": "processmap cosmos",
  "private": false,
  "scripts": {
    "rest-server": "node server.babel.js",
    "start": "webpack-dev-server --history-api-fallback --devtool eval-source-map --hot --inline --progress --colors",
    "build": "npm run clean && webpack --progress --colors",
    "build:prod": "npm run clean &&  NODE_ENV=production webpack --progress --colors",
    "build-old": "NODE_ENV=production && npm run clean && webpack -p",
    "clean": "rimraf build",
    "lint": "eslint ./",
    "test": "NODE_ENV=testing mocha --require ./test/test_helper 'src/**/*.spec.js'",
    "test:watch": "npm run test -- --watch",
    "git-update": "git update-index --again"
  },
  "precommit": {
    "run": "git-update, lint",
    "silent": true
  },
  "dependencies": {
    "babel-polyfill": "^6.23.0",
    "babel-runtime": "^6.23.0",
    "bootstrap": "^3.3.7",
    "copy-webpack-plugin": "^4.3.1",
    "enzyme": "^2.9.1",
    "expect": "^1.20.2",
    "expect-jsx": "^3.0.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "highcharts": "^5.0.12",
    "highcharts-more": "^0.1.2",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13",
    "prop-types": "^15.5.10",
    "prunk": "^1.3.0",
    "radium": "^0.19.1",
    "rc-datepicker": "^5.0.8",
    "rc-time-picker": "^2.4.1",
    "react": "^15.6.1",
    "react-addons-css-transition-group": "^15.6.0",
    "react-bootstrap": "^0.31.1",
    "react-bootstrap-switch": "^3.4.5",
    "react-click-outside": "^2.3.1",
    "react-datepicker": "^0.27.0",
    "react-dnd": "^2.4.0",
    "react-dnd-html5-backend": "^2.4.1",
    "react-dom": "^15.6.1",
    "react-dropzone": "^3.13.3",
    "react-dual-listbox": "^1.1.0",
    "react-fa": "^4.2.0",
    "react-grid-layout": "^0.14.6",
    "react-masonry-component": "^5.0.7",
    "react-pdf-js": "^2.0.5",
    "react-redux": "^5.0.5",
    "react-resizable": "^1.7.1",
    "react-router": "^3.0.5",
    "react-router-bootstrap": "^0.24.2",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^4.0.8",
    "react-select": "^0.9.1",
    "react-tap-event-plugin": "^2.0.1",
    "react-toastr": "2.8.2",
    "react-toggle-button": "^2.1.0",
    "react-treebeard": "1.1.4",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-mock-store": "^1.2.3",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.2.0",
    "velocity-react": "1.3.3",
    "whatwg-fetch": "^2.0.3",
    "xlsx": "^0.10.8"
  },
  "devDependencies": {
    "assert": "^1.4.1",
    "babel-core": "^6.25.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "body-parser": "^1.17.2",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.4",
    "es6-promise": "^4.1.1",
    "eslint": "^4.2.0",
    "eslint-config-airbnb": "^15.0.2",
    "eslint-plugin-babel": "^4.1.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-lodash": "^2.4.4",
    "eslint-plugin-react": "^7.1.0",
    "exports-loader": "^0.6.4",
    "express": "^4.15.3",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "fs-extra": "^4.0.0",
    "glob": "^7.1.2",
    "imports-loader": "^0.7.1",
    "jasmine": "^2.6.0",
    "jasmine-core": "^2.6.4",
    "jsdom": "^11.1.0",
    "mocha": "^3.4.2",
    "node-fetch": "^1.7.1",
    "node-sass": "^4.5.3",
    "pre-commit": "^1.2.2",
    "react-addons-test-utils": "^15.6.0",
    "react-clipboard.js": "^1.1.2",
    "react-hot-loader": "^1.3.1",
    "rimraf": "^2.6.1",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.18.2",
    "url-loader": "^0.5.9",
    "webpack": "^3.2.0",
    "webpack-dev-server": "^2.5.1",
    "win-node-env": "^0.1.0"
  },
  "comments": {
    "babel-core": "es6",
    "extract-text-webpack-plugin": "extract text/css from bundle into a file.",
    "fs-extra": "add extra methods such as mkdir -p, cp -r, and rm -rf",
    "glob": "match files using the patterns the shell uses, like stars and stuff.",
    "react-fa": "Font Awesome icons as React components.",
    "express": "The Express philosophy is to provide small, robust tooling for HTTP servers, making it a great solution for single page applications, web sites, hybrids, or public HTTP APIs.",
    "xlsx": "Read excel file content at client side.  http://codetheory.in/parse-read-excel-files-xls-xlsx-javascript/"
  }
}
